version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - MONGO_URI=mongodb://localhost/CRUD_books
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017

